import type { MenuItem, TableData, Order, InventoryItem, StaffMember, Reservation, AIInsight, User } from './types'

export const RESTAURANT_NAME = 'Ember & Oak'
export const RESTAURANT_TAGLINE = 'Farm-to-table dining, elevated.'

export const mockUser: User = {
  id: 'u001',
  name: 'Priya Sharma',
  email: 'priya@example.com',
  role: 'customer',
  loyaltyPoints: 1240,
  joinDate: '2023-08-15',
  avatar: 'PS',
  preferences: ['Window seat', 'Quiet section'],
  dietary: ['Vegetarian'],
}

export const mockManager: User = {
  id: 'm001',
  name: 'Marcus Chen',
  email: 'marcus@emberandoak.com',
  role: 'manager',
  loyaltyPoints: 0,
  joinDate: '2021-03-10',
  avatar: 'MC',
}

export const menuItems: MenuItem[] = [
  {
    id: 'mi001',
    name: 'Burrata & Heirloom Tomato',
    category: 'Starters',
    price: 18,
    description: 'Creamy burrata with heirloom tomatoes, aged balsamic, fresh basil oil, and sea salt flakes.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegetarian', 'Gluten-free'],
    prepTime: 8,
    rating: 4.8,
    reviews: 142,
    popular: true,
  },
  {
    id: 'mi002',
    name: 'Seared Scallops',
    category: 'Starters',
    price: 24,
    description: 'Hand-dived scallops, cauliflower purée, crispy capers, and preserved lemon butter.',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Gluten-free'],
    prepTime: 12,
    rating: 4.9,
    reviews: 98,
  },
  {
    id: 'mi003',
    name: 'Wild Mushroom Arancini',
    category: 'Starters',
    price: 14,
    description: 'Truffle-scented risotto balls, smoked paprika aioli, micro herbs.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegetarian'],
    prepTime: 10,
    rating: 4.6,
    reviews: 76,
  },
  {
    id: 'mi004',
    name: 'Oak-Smoked Duck Breast',
    category: 'Mains',
    price: 42,
    description: 'Slow-smoked duck breast, cherry gastrique, roasted celeriac, pickled red cabbage.',
    image: 'https://images.unsplash.com/photo-1546039907-7fa05f864c02?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Gluten-free'],
    prepTime: 22,
    rating: 4.9,
    reviews: 201,
    popular: true,
  },
  {
    id: 'mi005',
    name: 'Pan-Seared Halibut',
    category: 'Mains',
    price: 38,
    description: 'Line-caught halibut, saffron beurre blanc, asparagus, kohlrabi, and herb oil.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Gluten-free'],
    prepTime: 18,
    rating: 4.7,
    reviews: 134,
  },
  {
    id: 'mi006',
    name: 'Heritage Breed Pork Chop',
    category: 'Mains',
    price: 36,
    description: 'Brined Berkshire pork chop, apple cider jus, braised fennel, potato gratin.',
    image: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&h=400&fit=crop&auto=format',
    available: false,
    dietary: [],
    prepTime: 25,
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 'mi007',
    name: 'Roasted Cauliflower Steak',
    category: 'Mains',
    price: 28,
    description: 'Whole-roasted cauliflower, romesco, charred broccolini, almond crumble, za\'atar.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegan', 'Gluten-free'],
    prepTime: 20,
    rating: 4.5,
    reviews: 67,
    new: true,
  },
  {
    id: 'mi008',
    name: 'Dry-Aged Ribeye (250g)',
    category: 'Mains',
    price: 58,
    description: '35-day dry-aged ribeye, bone marrow butter, truffle fries, watercress.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Gluten-free'],
    prepTime: 28,
    rating: 5.0,
    reviews: 312,
    popular: true,
  },
  {
    id: 'mi009',
    name: 'Valrhona Chocolate Fondant',
    category: 'Desserts',
    price: 14,
    description: 'Warm 70% Valrhona fondant, Tahitian vanilla ice cream, salted caramel shards.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegetarian'],
    prepTime: 14,
    rating: 4.9,
    reviews: 287,
    popular: true,
  },
  {
    id: 'mi010',
    name: 'Seasonal Fruit Pavlova',
    category: 'Desserts',
    price: 12,
    description: 'Crisp meringue, clotted cream, passionfruit curd, seasonal berries, candied pistachios.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegetarian', 'Gluten-free'],
    prepTime: 8,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 'mi011',
    name: 'Affogato al Caffè',
    category: 'Desserts',
    price: 9,
    description: 'Double espresso poured over house-made fior di latte gelato, amaretti crumble.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegetarian', 'Gluten-free'],
    prepTime: 5,
    rating: 4.8,
    reviews: 203,
  },
  {
    id: 'mi012',
    name: 'Ember Old Fashioned',
    category: 'Drinks',
    price: 16,
    description: 'Smoked bourbon, demerara, Angostura & orange bitters, torched orange peel.',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegan', 'Gluten-free'],
    prepTime: 5,
    rating: 4.9,
    reviews: 178,
    popular: true,
  },
  {
    id: 'mi013',
    name: 'Garden Spritz',
    category: 'Drinks',
    price: 13,
    description: 'Aperol, elderflower, cucumber soda, fresh mint, edible flowers. (Non-alcoholic option available)',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegan', 'Gluten-free'],
    prepTime: 4,
    rating: 4.6,
    reviews: 94,
  },
  {
    id: 'mi014',
    name: 'Sommelier\'s Wine Pairing',
    category: 'Drinks',
    price: 48,
    description: 'Four curated wines matched to your meal progression by our sommelier.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=400&fit=crop&auto=format',
    available: true,
    dietary: ['Vegan'],
    prepTime: 3,
    rating: 4.8,
    reviews: 112,
  },
]

export const menuCategories = ['All', 'Starters', 'Mains', 'Desserts', 'Drinks']

export const tables: TableData[] = [
  { id: 't01', number: 1, capacity: 2, status: 'occupied', zone: 'indoor', seatedAt: '19:15', orderId: 'o001' },
  { id: 't02', number: 2, capacity: 2, status: 'available', zone: 'indoor' },
  { id: 't03', number: 3, capacity: 4, status: 'reserved', zone: 'indoor', reservation: { name: 'James Liu', time: '20:00', party: 3, phone: '+61 412 555 123' } },
  { id: 't04', number: 4, capacity: 4, status: 'occupied', zone: 'indoor', seatedAt: '18:45', orderId: 'o002' },
  { id: 't05', number: 5, capacity: 6, status: 'available', zone: 'indoor' },
  { id: 't06', number: 6, capacity: 6, status: 'occupied', zone: 'indoor', seatedAt: '19:30', orderId: 'o003' },
  { id: 't07', number: 7, capacity: 8, status: 'reserved', zone: 'private', reservation: { name: 'Corporate Event – TechCorp', time: '19:30', party: 8, phone: '+61 2 9555 0101' } },
  { id: 't08', number: 8, capacity: 2, status: 'cleaning', zone: 'outdoor' },
  { id: 't09', number: 9, capacity: 2, status: 'available', zone: 'outdoor' },
  { id: 't10', number: 10, capacity: 4, status: 'available', zone: 'outdoor' },
  { id: 't11', number: 11, capacity: 4, status: 'occupied', zone: 'outdoor', seatedAt: '19:00', orderId: 'o004' },
  { id: 't12', number: 12, capacity: 2, status: 'available', zone: 'private' },
]

export const orders: Order[] = [
  {
    id: 'o001',
    tableNumber: 1,
    customerId: 'u001',
    customerName: 'Priya Sharma',
    items: [
      { menuItemId: 'mi001', name: 'Burrata & Heirloom Tomato', price: 18, quantity: 1 },
      { menuItemId: 'mi008', name: 'Dry-Aged Ribeye (250g)', price: 58, quantity: 1 },
      { menuItemId: 'mi009', name: 'Valrhona Chocolate Fondant', price: 14, quantity: 2 },
      { menuItemId: 'mi012', name: 'Ember Old Fashioned', price: 16, quantity: 2 },
    ],
    status: 'preparing',
    total: 140,
    createdAt: '2026-11-15T19:12:00',
    estimatedMinutes: 8,
    type: 'dine-in',
    paymentStatus: 'unpaid',
  },
  {
    id: 'o002',
    tableNumber: 4,
    customerId: 'u002',
    customerName: 'Sophie Andreou',
    items: [
      { menuItemId: 'mi002', name: 'Seared Scallops', price: 24, quantity: 2 },
      { menuItemId: 'mi004', name: 'Oak-Smoked Duck Breast', price: 42, quantity: 1 },
      { menuItemId: 'mi005', name: 'Pan-Seared Halibut', price: 38, quantity: 1 },
    ],
    status: 'ready',
    total: 128,
    createdAt: '2026-11-15T18:38:00',
    estimatedMinutes: 0,
    type: 'dine-in',
    paymentStatus: 'unpaid',
  },
  {
    id: 'o003',
    tableNumber: 6,
    customerId: 'u003',
    customerName: 'Marcus Webb',
    items: [
      { menuItemId: 'mi003', name: 'Wild Mushroom Arancini', price: 14, quantity: 3 },
      { menuItemId: 'mi007', name: 'Roasted Cauliflower Steak', price: 28, quantity: 2 },
      { menuItemId: 'mi010', name: 'Seasonal Fruit Pavlova', price: 12, quantity: 2 },
      { menuItemId: 'mi013', name: 'Garden Spritz', price: 13, quantity: 4 },
    ],
    status: 'confirmed',
    total: 146,
    createdAt: '2026-11-15T19:28:00',
    estimatedMinutes: 18,
    type: 'dine-in',
    paymentStatus: 'unpaid',
  },
  {
    id: 'o004',
    tableNumber: 11,
    customerId: 'u004',
    customerName: 'Lena Fischer',
    items: [
      { menuItemId: 'mi001', name: 'Burrata & Heirloom Tomato', price: 18, quantity: 1 },
      { menuItemId: 'mi008', name: 'Dry-Aged Ribeye (250g)', price: 58, quantity: 2 },
      { menuItemId: 'mi012', name: 'Ember Old Fashioned', price: 16, quantity: 2 },
    ],
    status: 'pending',
    total: 166,
    createdAt: '2026-11-15T19:41:00',
    estimatedMinutes: 25,
    type: 'dine-in',
    paymentStatus: 'unpaid',
  },
  {
    id: 'o005',
    tableNumber: undefined,
    customerId: 'u005',
    customerName: 'Ryan O\'Brien',
    items: [
      { menuItemId: 'mi004', name: 'Oak-Smoked Duck Breast', price: 42, quantity: 1 },
      { menuItemId: 'mi011', name: 'Affogato al Caffè', price: 9, quantity: 1 },
    ],
    status: 'delivered',
    total: 51,
    createdAt: '2026-11-15T18:00:00',
    estimatedMinutes: 0,
    type: 'takeaway',
    paymentStatus: 'paid',
  },
]

export const inventory: InventoryItem[] = [
  { id: 'inv001', name: 'Burrata (250g)', category: 'Dairy', unit: 'units', currentStock: 8, minStock: 10, maxStock: 30, costPerUnit: 7.50, supplier: 'Bulla Dairy', lastRestocked: '2026-11-14', expiryDays: 3 },
  { id: 'inv002', name: 'Dry-Aged Ribeye', category: 'Meat', unit: 'kg', currentStock: 4.5, minStock: 5, maxStock: 15, costPerUnit: 65, supplier: 'Greenfields Meats', lastRestocked: '2026-11-13', expiryDays: 5 },
  { id: 'inv003', name: 'Valrhona Dark 70%', category: 'Pantry', unit: 'kg', currentStock: 2.8, minStock: 2, maxStock: 8, costPerUnit: 22, supplier: 'Gourmet Direct', lastRestocked: '2026-11-10' },
  { id: 'inv004', name: 'Wild Mushroom Mix', category: 'Produce', unit: 'kg', currentStock: 1.2, minStock: 2, maxStock: 6, costPerUnit: 18, supplier: 'Forest Gourmet', lastRestocked: '2026-11-14', expiryDays: 4 },
  { id: 'inv005', name: 'Line-Caught Halibut', category: 'Seafood', unit: 'kg', currentStock: 6.0, minStock: 4, maxStock: 12, costPerUnit: 48, supplier: 'Ocean Fresh Co.', lastRestocked: '2026-11-15', expiryDays: 2 },
  { id: 'inv006', name: 'Heirloom Tomatoes', category: 'Produce', unit: 'kg', currentStock: 3.5, minStock: 3, maxStock: 10, costPerUnit: 8, supplier: 'Heritage Farms', lastRestocked: '2026-11-15', expiryDays: 5 },
  { id: 'inv007', name: 'Bourbon (Woodford Reserve)', category: 'Spirits', unit: 'bottles', currentStock: 4, minStock: 3, maxStock: 12, costPerUnit: 58, supplier: 'Premium Beverages', lastRestocked: '2026-11-08' },
  { id: 'inv008', name: 'Truffle Oil', category: 'Pantry', unit: 'bottles', currentStock: 2, minStock: 3, maxStock: 8, costPerUnit: 32, supplier: 'Gourmet Direct', lastRestocked: '2026-11-01' },
  { id: 'inv009', name: 'Fresh Scallops', category: 'Seafood', unit: 'kg', currentStock: 0.8, minStock: 2, maxStock: 6, costPerUnit: 62, supplier: 'Ocean Fresh Co.', lastRestocked: '2026-11-14', expiryDays: 1 },
  { id: 'inv010', name: 'Duck Breasts', category: 'Meat', unit: 'units', currentStock: 12, minStock: 8, maxStock: 24, costPerUnit: 14, supplier: 'Greenfields Meats', lastRestocked: '2026-11-14', expiryDays: 3 },
  { id: 'inv011', name: 'Arborio Rice', category: 'Pantry', unit: 'kg', currentStock: 8, minStock: 4, maxStock: 15, costPerUnit: 4, supplier: 'Pantry Essentials', lastRestocked: '2026-10-28' },
  { id: 'inv012', name: 'Asparagus', category: 'Produce', unit: 'bunches', currentStock: 5, minStock: 4, maxStock: 12, costPerUnit: 6, supplier: 'Heritage Farms', lastRestocked: '2026-11-15', expiryDays: 4 },
]

export const staff: StaffMember[] = [
  { id: 's001', name: 'Marcus Chen', role: 'General Manager', department: 'Management', shift: '10:00–22:00', status: 'on-duty', phone: '+61 412 001 001', rating: 4.9, startDate: '2021-03-10', hoursThisWeek: 42, avatar: 'MC' },
  { id: 's002', name: 'Isabelle Fontaine', role: 'Head Chef', department: 'Kitchen', shift: '14:00–23:00', status: 'on-duty', phone: '+61 412 001 002', rating: 4.8, startDate: '2021-05-01', hoursThisWeek: 38, avatar: 'IF' },
  { id: 's003', name: 'Raj Patel', role: 'Sous Chef', department: 'Kitchen', shift: '14:00–23:00', status: 'on-duty', phone: '+61 412 001 003', rating: 4.7, startDate: '2022-01-15', hoursThisWeek: 40, avatar: 'RP' },
  { id: 's004', name: 'Amara Osei', role: 'Sommelier', department: 'Front of House', shift: '16:00–23:00', status: 'on-duty', phone: '+61 412 001 004', rating: 4.9, startDate: '2022-06-20', hoursThisWeek: 35, avatar: 'AO' },
  { id: 's005', name: 'Tom Nakamura', role: 'Senior Waiter', department: 'Front of House', shift: '16:00–23:00', status: 'break', phone: '+61 412 001 005', rating: 4.6, startDate: '2022-09-01', hoursThisWeek: 37, avatar: 'TN' },
  { id: 's006', name: 'Chloe Martin', role: 'Waiter', department: 'Front of House', shift: '16:00–23:00', status: 'on-duty', phone: '+61 412 001 006', rating: 4.5, startDate: '2023-02-14', hoursThisWeek: 32, avatar: 'CM' },
  { id: 's007', name: 'Daniel Park', role: 'Bartender', department: 'Bar', shift: '16:00–01:00', status: 'on-duty', phone: '+61 412 001 007', rating: 4.8, startDate: '2022-11-01', hoursThisWeek: 40, avatar: 'DP' },
  { id: 's008', name: 'Fatima Al-Hassan', role: 'Host', department: 'Front of House', shift: '17:00–23:00', status: 'on-duty', phone: '+61 412 001 008', rating: 4.7, startDate: '2023-05-10', hoursThisWeek: 30, avatar: 'FA' },
]

export const reservations: Reservation[] = [
  { id: 'r001', customerName: 'James Liu', customerEmail: 'james@email.com', customerPhone: '+61 412 555 123', date: '2026-11-15', time: '20:00', partySize: 3, tableId: 't03', status: 'confirmed' },
  { id: 'r002', customerName: 'Corporate Event – TechCorp', customerEmail: 'events@techcorp.com', customerPhone: '+61 2 9555 0101', date: '2026-11-15', time: '19:30', partySize: 8, tableId: 't07', status: 'seated', specialRequests: 'Vegan menu for 2 guests' },
  { id: 'r003', customerName: 'Yuki Tanaka', customerEmail: 'yuki@email.com', customerPhone: '+61 412 777 888', date: '2026-11-16', time: '18:30', partySize: 2, status: 'confirmed', specialRequests: 'Anniversary dinner — flower arrangement please' },
  { id: 'r004', customerName: 'Ahmed Hassan', customerEmail: 'ahmed@email.com', customerPhone: '+61 412 999 000', date: '2026-11-16', time: '19:00', partySize: 4, status: 'pending' },
  { id: 'r005', customerName: 'Clara Bernstein', customerEmail: 'clara@email.com', customerPhone: '+61 412 111 222', date: '2026-11-16', time: '19:30', partySize: 6, status: 'confirmed' },
]

export const weeklyRevenue = [
  { day: 'Mon', lunch: 2400, dinner: 5800, total: 8200 },
  { day: 'Tue', lunch: 1900, dinner: 6100, total: 8000 },
  { day: 'Wed', lunch: 2800, dinner: 7200, total: 10000 },
  { day: 'Thu', lunch: 3100, dinner: 8400, total: 11500 },
  { day: 'Fri', lunch: 4200, dinner: 12800, total: 17000 },
  { day: 'Sat', lunch: 5600, dinner: 15200, total: 20800 },
  { day: 'Sun', lunch: 4800, dinner: 11400, total: 16200 },
]

export const topDishes = [
  { name: 'Dry-Aged Ribeye', orders: 47, revenue: 2726, growth: 12 },
  { name: 'Valrhona Fondant', orders: 62, revenue: 868, growth: 8 },
  { name: 'Ember Old Fashioned', orders: 89, revenue: 1424, growth: 22 },
  { name: 'Oak-Smoked Duck', orders: 38, revenue: 1596, growth: 5 },
  { name: 'Burrata & Tomato', orders: 71, revenue: 1278, growth: 18 },
]

export const aiInsights: AIInsight[] = [
  {
    id: 'ai001',
    type: 'alert',
    title: 'Critical Stock: Scallops & Truffle Oil',
    description: 'Fresh scallops drop to 0.8 kg — below service threshold for tonight\'s reservations (est. 12 scallop dishes needed). Truffle oil also running low at 2 bottles.',
    impact: 'high',
    category: 'Inventory',
    actionable: true,
    action: 'Contact Ocean Fresh Co. for emergency delivery',
    confidence: 97,
    createdAt: '2026-11-15T19:00:00',
  },
  {
    id: 'ai002',
    type: 'prediction',
    title: 'Saturday Peak: Ribeye Demand +34%',
    description: 'Based on reservation data and historical Saturday patterns, expect 34% higher ribeye orders this weekend. Current stock (4.5 kg) may fall short by ~1.2 kg.',
    impact: 'high',
    category: 'Demand Forecast',
    actionable: true,
    action: 'Order additional 3 kg from Greenfields Meats',
    confidence: 89,
    createdAt: '2026-11-15T18:30:00',
  },
  {
    id: 'ai003',
    type: 'recommendation',
    title: 'Dynamic Pricing Opportunity — Friday Dinner',
    description: 'Table fill rate on Fridays is 97% with a 2-hour average wait. Introducing a peak-time surcharge of 8–12% on Fridays 18:30–21:30 could add ~$1,800/week revenue.',
    impact: 'medium',
    category: 'Revenue',
    actionable: true,
    action: 'Review and enable dynamic pricing in settings',
    confidence: 76,
    createdAt: '2026-11-15T17:00:00',
  },
  {
    id: 'ai004',
    type: 'trend',
    title: 'Vegan Menu Demand Rising — 28% MoM',
    description: 'Vegan dish orders have grown 28% month-over-month. The Roasted Cauliflower Steak (your newest addition) already accounts for 18% of all main orders in its first week.',
    impact: 'medium',
    category: 'Menu Analytics',
    actionable: true,
    action: 'Consider expanding vegan mains by 2 dishes next quarter',
    confidence: 92,
    createdAt: '2026-11-15T16:00:00',
  },
  {
    id: 'ai005',
    type: 'recommendation',
    title: 'Staff Scheduling Gap — Sunday Lunch',
    description: 'Sunday lunch covers have increased 31% over 8 weeks, but FOH staffing remains at the same level. Guest-to-staff ratio is now 9:1 vs. your 6:1 target.',
    impact: 'medium',
    category: 'Staffing',
    actionable: true,
    action: 'Add 1 waiter and 1 host to Sunday lunch shift',
    confidence: 84,
    createdAt: '2026-11-15T15:00:00',
  },
  {
    id: 'ai006',
    type: 'trend',
    title: 'Cocktail Attachment Rate Up 41%',
    description: 'Since introducing the Ember Old Fashioned, cocktail attachment (% of diners ordering at least one) jumped from 38% to 54%. Bartender Daniel Park\'s upselling contributes significantly.',
    impact: 'low',
    category: 'Performance',
    actionable: false,
    confidence: 95,
    createdAt: '2026-11-15T14:00:00',
  },
]

export const customerList = [
  { id: 'cu001', name: 'Priya Sharma', email: 'priya@example.com', visits: 24, totalSpend: 4820, lastVisit: '2026-11-10', loyaltyTier: 'Gold', dietary: ['Vegetarian'] },
  { id: 'cu002', name: 'Sophie Andreou', email: 'sophie@example.com', visits: 12, totalSpend: 2340, lastVisit: '2026-11-15', loyaltyTier: 'Silver', dietary: [] },
  { id: 'cu003', name: 'Marcus Webb', email: 'marcus.w@example.com', visits: 8, totalSpend: 1680, lastVisit: '2026-11-15', loyaltyTier: 'Bronze', dietary: ['Vegan'] },
  { id: 'cu004', name: 'Lena Fischer', email: 'lena@example.com', visits: 31, totalSpend: 7210, lastVisit: '2026-11-15', loyaltyTier: 'Platinum', dietary: ['Gluten-free'] },
  { id: 'cu005', name: "Ryan O'Brien", email: 'ryan@example.com', visits: 6, totalSpend: 890, lastVisit: '2026-11-15', loyaltyTier: 'Bronze', dietary: [] },
  { id: 'cu006', name: 'Yuki Tanaka', email: 'yuki@email.com', visits: 15, totalSpend: 3100, lastVisit: '2026-11-08', loyaltyTier: 'Silver', dietary: [] },
  { id: 'cu007', name: 'Ahmed Hassan', email: 'ahmed@email.com', visits: 4, totalSpend: 620, lastVisit: '2026-10-28', loyaltyTier: 'Bronze', dietary: ['Halal'] },
]
